version: '3.8'

services:
  web:
    build: .          # 🚀 สั่งให้อ่านไฟล์ Dockerfile เพื่อติดตั้ง PDO
    container_name: hw11_helpdesk_web
    ports:
      - "8092:80"     # 🚀 พอร์ตหน้าเว็บของนาย A คือ 8092
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: hw11_helpdesk_db
    ports:
      - "8093:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: helpdesk_db
      MYSQL_USER: dev_user
      MYSQL_PASSWORD: dev_password
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: hw11_helpdesk_pma
    ports:
      - "8094:80"     # 🚀 พอร์ต phpMyAdmin ของนาย B คือ 8094
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db

volumes:
  db_data:
